### ISSUE TITLE
你好，请问下大王卡查询流量还能用吗我这边查出来是空的

### ISSUE THREAD

**Issue by gsons** [Demon1630/python-practice#1]
我这边查出来是空的 `{"code":"0","message":"成功","data":{"phone":null,"productName":null,"superVip":false,"fee":{"used":null,"left":null},"voice":{"used":null,"left":null},"flow":{"superVip":{"used":null,"left":null,"total":null,"count":0},"specificPkg":{"used":null,"left":null,"total":null,"count":0},"nationalPkg":{"used":null,"left":null,"total":null,"count":0},"rzb":{"used":null,"left":null,"total":null,"count":0},"yzb":{"used":null,"left":null,"total":null,"count":0},"flexy":{"used":null,"left":null,"total":null,"count":0}},"totalUsed":null,"totalLeft":null}}`

**Comment by Demon1630** [comment]
最好自己使用fiddler来抓取数据，然后针对修改python文件
